# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Configure git status to behave like posh-git
[git_status]
conflicted = "≠${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = '✓'

untracked = "?${count} "
stashed = '\$${count} '
modified = "!${count} "
staged = "[+$count](green) "
renamed = "[»$count](green) "
deleted = "-$count " # Both unstaged and staged
